// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeStation():Promise<void>;

export function GetVolume():Promise<number>;

export function SetVolume(arg1:number):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
